version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "12:00"
      timezone: "Asia/Kolkata"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "12:00"
      timezone: "Asia/Kolkata"
