# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "12:00"
      timezone: "Asia/Kolkata"
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "12:00"
      timezone: "Asia/Kolkata"
    ignore:
      - dependency-name: "androidx.test:runner"
        versions: ["1.3.x", "1.4.x", "1.5.x"]
      - dependency-name: "androidx.test.espresso:espresso-core"
        versions: ["3.3.x", "3.4.x", "3.5.x"]

# To search in PR for ignored dependencies
# is:pr commenter:hrishikesh-kadam "@dependabot ignore" in:comments
