# TODO(hrishikesh-kadam): Make a pub package like very_good_analysis
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_super_parameters: true
    prefer_relative_imports: true
    directives_ordering: true

analyzer:
  errors:
    todo: ignore
