targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names
          preamble: // coverage:ignore-file
      mockito|mockBuilder:
        generate_for:
          include:
            - test/**
            - integration_test/**
