targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names
          preamble: // coverage:ignore-file
      mockito|mockBuilder:
        generate_for:
          include:
            - test/**
            # - integration_test/**
      # https://github.com/google/json_serializable.dart/tree/master/json_serializable#build-configuration
      # https://github.com/google/json_serializable.dart/blob/master/json_annotation/lib/src/json_serializable.dart
      json_serializable:
        options:
          include_if_null: false
