# Note: jobs of ci-contributors.yml and ci-schedule.yml should be in sync
name: ci-contributors

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macos-13'
      ref:
        description: 'Flutter channel, version or git reference'
        required: true
        default: 'stable'
        type: choice
        options:
          - 'stable'
          - 'beta'
          - 'main'
          - 'master'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI on ${{ inputs.runner || matrix.runner }} using Flutter ${{ inputs.ref || matrix.ref }}
    if: github.triggering_actor != 'dependabot[bot]'
    runs-on: ${{ inputs.runner || matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest ]
        ref: [ stable, beta ]

    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'

      - run: echo '${{ toJSON(github) }}'

      - id: get-checkout-ref
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            CHECKOUT_REF="$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")"
          else
            CHECKOUT_REF="$GITHUB_REF_NAME"
          fi
          echo "CHECKOUT_REF=$CHECKOUT_REF" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-checkout-ref.outputs.CHECKOUT_REF }}

      - uses: hrishikesh-kadam/setup-flutter@v1
        with:
          ref: ${{ inputs.ref || matrix.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: ./tool/prerequisite.sh --contributor

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ inputs.runner || matrix.runner }}-flutter-${{ inputs.ref || matrix.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - run: ./tool/ci.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          name: ${{ inputs.runner || matrix.runner }}-${{ inputs.ref || matrix.ref }}

      - run: ./tool/web/deploy.sh
        if: ${{ inputs.ref || matrix.ref }} == 'stable'
        env:
          FIREBASE_CONTRI_KEY: ${{ secrets.FIREBASE_CONTRI_KEY }}

      - run: ./tool/android/stop-gradle.sh
