# Note: jobs of ci-contributors.yml, ci-schedule.yml and ci-dispatch.yml should be in sync
name: ci-dispatch

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macOS-13'
      ref:
        description: 'Flutter channel, version or git reference'
        required: true
        default: 'stable'
        type: choice
        options:
          - 'stable'
          - 'beta'
          - 'master'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI on ${{ inputs.runner }} using Flutter ${{ inputs.ref }}
    runs-on: ${{ inputs.runner }}

    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'

      - uses: actions/checkout@v3

      - uses: hrishikesh-kadam/setup-flutter@v1
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: ./tool/prerequisite.sh --minimal

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ inputs.runner }}-flutter-${{ inputs.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - run: ./tool/ci.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          name: ${{ inputs.runner }}-${{ inputs.ref }}

      - run: ./tool/android/stop-gradle.sh
