# Note: jobs of ci-contributors.yml and ci-schedule.yml should be in sync
name: ci-schedule

on:
  schedule:
    # 12:00 PM IST / 6:30 AM GMT every 6th day over the year with following conditions.
    # GitHub will remove any cache entries that have not been accessed in over 7 days.
    # 1. 1 day early in March on 5th for non leap year adjustment.
    # 2. To not continue cache in next year remove 30 from December.
    - cron: '30 6 5,11,17,23,29 1 *'
    - cron: '30 6 4,10,16,22,28 2 *'
    - cron: '30 6 5,11,17,23,29 3 *'
    - cron: '30 6 4,10,16,22,28 4 *'
    - cron: '30 6 4,10,16,22,28 5 *'
    - cron: '30 6 3,9,15,21,27 6 *'
    - cron: '30 6 3,9,15,21,27 7 *'
    - cron: '30 6 2,8,14,20,26 8 *'
    - cron: '30 6 1,7,13,19,25 9 *'
    - cron: '30 6 1,7,13,19,25,31 10 *'
    - cron: '30 6 6,12,18,24,30 11 *'
    - cron: '30 6 6,12,18,24,30 12 *'
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner OS'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
          - 'macos-13'
      ref:
        description: 'Flutter channel, version or git reference'
        required: true
        default: 'stable'
        type: choice
        options:
          - 'stable'
          - 'beta'
          - 'main'
          - 'master'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: CI on ${{ inputs.runner || matrix.runner }} using Flutter ${{ inputs.ref || matrix.ref }}
    runs-on: ${{ inputs.runner || matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest, windows-latest ]
        ref: [ stable ]
        include:
          - runner: ubuntu-latest
            ref: beta

    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'

      - run: echo '${{ toJSON(github) }}'

      - id: get-checkout-ref
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            CHECKOUT_REF="$(jq -r .pull_request.head.ref "$GITHUB_EVENT_PATH")"
          else
            CHECKOUT_REF="$GITHUB_REF_NAME"
          fi
          echo "CHECKOUT_REF=$CHECKOUT_REF" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-checkout-ref.outputs.CHECKOUT_REF }}

      - uses: hrishikesh-kadam/setup-flutter@v1
        with:
          ref: ${{ inputs.ref || matrix.ref }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: ./tool/prerequisite.sh --minimal

      # https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ inputs.runner || matrix.runner }}-flutter-${{ inputs.ref || matrix.ref }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - run: ./tool/ci.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          name: ${{ inputs.runner || matrix.runner }}-${{ inputs.ref || matrix.ref }}

      - run: ./tool/android/stop-gradle.sh
