name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # 12:00 PM IST / 6:30 AM GMT every Sunday and Wednesday.
    # GitHub will remove any cache entries that have not been accessed in over 7 days.
    - cron: '30 6 * * 0,3'

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: ci on ${{ matrix.runner }} using Flutter ${{ matrix.ref }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ubuntu-latest ]
        ref: [ stable, beta ]

    steps:
      - name: Setup Flutter
        uses: hrishikesh-kadam/setup-flutter@v1
        with:
          ref: ${{ matrix.ref }}

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - uses: actions/checkout@v3

      - run: ./tool/ci.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          name: ${{ matrix.runner }}-${{ matrix.ref }}

      - id: build-web-deploy
        env:
          FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER_PROD: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER }}
          FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER_STAG: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER_STAG }}
          FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER_DEV: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER_DEV }}
        run: ./tool/build-web-deploy.sh

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: ${{ matrix.ref == 'stable' }}
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT_SPACE_DATA_EXPLORER }}
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          channelId: ${{ env.FIREBASE_CHANNEL_ID }}
          expires: 30d
